# -*- coding: utf-8 -*-
"""Funções.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wEHBuYyqtnzXEmDoZAcHMQ9AjID_Y-YE
"""

#Exercicio 1 - João Pedro Felix
def saudacao(nome):
    print(f"Olá, {nome}! Seja bem-vindo.")
saudacao("Joao Felix")

#Exercicio 2 - João Pedro Felix
def somar(a, b):
    return a + b
resultado = somar(15, 3)
print("Soma:", resultado)

#Exercicio 3 - João Pedro Felix
def par_ou_impar(numero):
    if numero % 2 == 0:
        return "Par"
    else:
        return "Ímpar"
print(par_ou_impar(15))

#Exercicio 4 - João Pedro Felix
def fatorial(n):
    resultado = 1
    for i in range(1, n + 1):
        resultado *= i
    return resultado
print("Fatorial:", fatorial(7))

#Exercicio 5 - João Pedro Felix
def exibir_nomes(lista):
    for nome in lista:
        print(nome)
nomes = ["Pedro", "Kaue", "João"]
exibir_nomes(nomes)