# -*- coding: utf-8 -*-
"""Laços de Repetição.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kHh-wXwBVSfnbZshKb4Iq0kobhaMMMus
"""

#Exercicio 1 - João Pedro Felix
for i in range(1, 11):
    print(i)

#Exercicio 2 - João Pedro Felix
num = 0
while num <= 20:
    if num % 2 == 0:
        print(num)
    num += 1

#Exercicio 3 - João Pedro Felix
soma = 0
for i in range(5):
    numero = int(input(f"Digite o {i+1}º número: "))
    soma += numero
print("Soma dos números:", soma)

#Exercicio 4 - João Pedro Felix
while True:
    palavra = input("Digite uma palavra (ou 'sair' para encerrar): ")
    if palavra.lower() == "sair":
        break
    print("Você digitou:", palavra)

#Exercicio 5 - João Pedro Felix
numero = int(input("Digite um número para ver a tabuada: "))
for i in range(1, 11):
    print(f"{numero} x {i} = {numero * i}")