# -*- coding: utf-8 -*-
"""Operações Condicionais.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DtyNvFtp8KLEbSoZsUfsHq22FLwv2Z46
"""

#Exercicio 1 - João Pedro Felix
idade = int(input("Digite sua idade: "))
if idade >= 18:
    print("Você é maior de idade.")
else:
    print("Você é menor de idade.")

#Exercicio 2 - João Pedro Felix
a = int(input("Digite o primeiro número: "))
b = int(input("Digite o segundo número: "))

if a > b:
    print("O maior número é:", a)
elif b > a:
    print("O maior número é:", b)
else:
    print("Os dois números são iguais.")

#Exercicio 3 - João Pedro Felix
media = float(input("Digite a média do aluno: "))
if media >= 7:
    print("Aluno aprovado!")
else:
    print("Aluno reprovado.")

#Exercicio 4 - João Pedro Felix
numero = float(input("Digite um número: "))

if numero > 0:
    print("Número positivo.")
elif numero < 0:
    print("Número negativo.")
else:
    print("Número zero.")

#Exercicio 5 - João Pedro Felix
senha = input("Digite a senha: ")
if senha == "100811":
    print("Acesso permitido.")
else:
    print("Senha incorreta.")

#Exercicio 6 - João Pedro Felix
print("1 - Saque\n2 - Depósito\n3 - Sair")
opcao = input("Escolha uma opção: ")

if opcao == "1":
    print("Você escolheu Saque.")
elif opcao == "2":
    print("Você escolheu Depósito.")
elif opcao == "3":
    print("Saindo...")
else:
    print("Opção inválida.")

#Exercicio 7 - João Pedro Felix
dia = int(input("Digite um número de 1 a 7: "))

if dia == 1:
    print("Domingo")
elif dia == 2:
    print("Segunda-feira")
elif dia == 3:
    print("Terça-feira")
elif dia == 4:
    print("Quarta-feira")
elif dia == 5:
    print("Quinta-feira")
elif dia == 6:
    print("Sexta-feira")
elif dia == 7:
    print("Sábado")
else:
    print("Número inválido.")

#Exercicio 8 - João Pedro Felix
letra = input("Digite uma letra: ").lower()

if letra in "aeiou":
    print("Vogal")
elif letra.isalpha():
    print("Consoante")
else:
    print("Isso não é uma letra.")

#Exercicio 9 - João Pedro Felix
n1 = float(input("Digite o primeiro número: "))
n2 = float(input("Digite o segundo número: "))
operacao = input("Digite a operação (+, -, *, /): ")

if operacao == "+":
    print("Resultado:", n1 + n2)
elif operacao == "-":
    print("Resultado:", n1 - n2)
elif operacao == "*":
    print("Resultado:", n1 * n2)
elif operacao == "/":
    if n2 != 0:
        print("Resultado:", n1 / n2)
    else:
        print("Erro: divisão por zero.")
else:
    print("Operação inválida.")

#Exercicio 10 - João Pedro Felix
escolha = int(input("Escolha seu personagem (1 - Neymar, 2 - Cristiano Ronaldo, 3 - Messi): "))

if escolha == 1:
    print("Você escolheu: Neymar")
elif escolha == 2:
    print("Você escolheu: Cristiano Ronaldo")
elif escolha == 3:
    print("Você escolheu: Messi")
else:
    print("Personagem inválido.")